# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True



    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('url', models.CharField(max_length=255)),
                ('css_class', models.CharField(max_length=255)),
                ('display_order', models.IntegerField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, to='auth.Group')),
                ('menu_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_children', to='menu.MenuItem')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(to='auth.Group')),
            ],
        ),
    ]
