# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_is', models.BooleanField()),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='is_admin', to='auth.Group')),
            ],
        ),
    ]
