# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
