# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20160222_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
