# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20160224_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='css_calss',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
