# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitem_css_calss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='css_calss',
            new_name='css_class',
        ),
    ]
