# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20160304_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='display_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
