# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menuitem_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['display_order']},
        ),
    ]
