# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('menu', '0007_auto_20160306_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
