# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('menu', '0008_menuitem_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(to='auth.Group')),
            ],
        ),
    ]
