# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-29 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
