# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-26 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_auto_20160629_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='name_en',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_pt',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
