# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20170427_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='name_es',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
