# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_auto_20170427_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='name_pt',
            new_name='name_pt_br',
        ),
    ]
